# Biblioteki numpy i pandas

Szymon Dziubak

### Numpy
Pozwala na pracę tabelami i macierzami.<br>
Rozwinięcie skrótu: Numerical Python

In [2]:
#Import biblioteki 
import numpy as np #alias: np

In [4]:
#Tablice NumPy
tablica = np.array([1,2,3,4,5,6])
print(tablica)
print(type(tablica))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [8]:
#Arange - tablica z elementami (od, do, krok)
tablica_arange = np.arange(1,11,2) #jak w range() element skrajny nie wchodzi w skłąd tablicy
print(tablica_arange)

[1 3 5 7 9]


In [14]:
#zeros - tablica złożona z zer
p = np.zeros(3)
print(p)
print("\n---------------\n")
p_wielowymiarowa = np.zeros((3,3))
print(p_wielowymiarowa)


[0. 0. 0.]

---------------

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
#ones - tablica wypełniona jedynkami
q = np.ones(3)
print(q)
print("\n---------------\n")
q_wielowymiarowa = np.ones((3,3))
print(q_wielowymiarowa)

[1. 1. 1.]

---------------

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
#full - tworzy tablicę wypełnioną stałymi
r = np.full(2,3) #2 elementy, trójki
print(r)
print("\n---------------\n")
r_wielowymiarowa = np.full((2,2),3)
print(r_wielowymiarowa)

[3 3]

---------------

[[3 3]
 [3 3]]


In [19]:
#eye - macierz jednostkowa
s = np.eye(4)
print(s)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
#random - tablica wypełniona wartościami losowymi
t = np.random.random(3)
print(t)
print("\n---------------\n")
t_wielowymiarowa = np.random.random((3,3))
print(t_wielowymiarowa)

[0.89224846 0.41410008 0.43773544]

---------------

[[0.98125634 0.82956141 0.30860442]
 [0.62809798 0.22777064 0.29515798]
 [0.70803151 0.77979955 0.6080523 ]]


In [24]:
#tablice indeksowane są jak listy
#tablice zaweirają tylko jeden typ danych
#możemy korzystać z operacji wektorowych
print(type(t)) #typ obiektu
print(t.dtype) #typ danych / elementów
print(t.shape) #wymiar tablicy
print(t_wielowymiarowa.shape)

<class 'numpy.ndarray'>
float64
(3,)
(3, 3)


In [26]:
#tworzenie macierzy od zera
a = np.array([[5,6], [7,8]])
print(a)
print(a[0,0])
print(a[0,1]) #0 wiersz, 1 kolumna
print(a[1,0])
print(a[1,1])

[[5 6]
 [7 8]]
5
6
7
8


Główne numeryczne typy danych tablic NumPy<br>
Im większy typ danych tym więcej miejsca zajmuje<br>
bool - True/False<br>
int8 - od -2^7 do 2^7 - 1<br>
int16 - od -2^15 do 2^15 - 1<br>
int32 - od -2^31 do 2^31 - 1<br>
int64 - od -2^63 do 2^63 - 1<br>
float16<br>
float32<br>
float64 lub float<br>
complex64 - zespolone<br>
complex128 lub complex zespolone<br>

In [32]:
#Każdy typ danych można poddać konwersji
print(np.float16(False))
print(np.bool(3))
print(np.int16(999.9))

0.0
True
999


C:\Users\BPOL_1~1\AppData\Local\Temp/ipykernel_17420/36486564.py:3: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(np.bool(3))


In [41]:
tab = np.arange(1,11,3, dtype = np.int8) #tworzymy tablicę ze zdefiniowanym typem danych
print(tab.dtype.itemsize) #rozmiar danych w bajtach

tab = np.arange(1,18,3, dtype = np.int32) 
print(tab.dtype.itemsize) #rozmiar danych w bajtach

1
4


In [43]:
#reshape - zmiana wymiaru tablicy
arr = np.arange(12)
print(arr)

new_arr = arr.reshape(4,3) #4 wiersze, 3 kolumny
print(new_arr)

new_arr2 = arr.reshape(3,4) #3 wiersze, 4 kolumny
print(new_arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [45]:
#flatten - przekształcenie na macierz jednowymiarową
arr = np.arange(1,10).reshape(3,3)
print(arr.flatten())

[1 2 3 4 5 6 7 8 9]


In [47]:
#transpose - transpozycja, zamiana wierszy z kolumnami
arr = np.arange(1,10).reshape(3,3)
print(arr.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [74]:
#operacje na tablicach 
tablica = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
tablica2 = np.arange(1,10).reshape(3,3)
print(tablica)
print("---")
print(tablica*2) #operacje na każdym elemencie
print("---")
print(tablica+8) #operacje na każdym elemencie
print("---")
print(tablica+tablica2) #dodawanie tablic
print("---")
print(tablica*tablica2) #mnożenie tablic


[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
---
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
---
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
---
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [62]:
#Łączenie tablic

#w poziomie
print("W poziomie")
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)*10
hs = np.hstack((arr1, arr2))
print(np.hstack((arr1, arr2)))
print("---")
print(np.concatenate((arr1, arr2), axis = 1))
print("""
---
""")
#w pionie
print("W pionie")
vs = np.vstack((arr1, arr2))
print(np.vstack((arr1, arr2)))
print("---")
print(np.concatenate((arr1, arr2), axis = 0))


W poziomie
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]
 [ 7  8  9 70 80 90]]
---
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]
 [ 7  8  9 70 80 90]]

---

W pionie
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]
---
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]


In [64]:
#Rozdzielanie tablic

#w poziomie
print("W poziomie")
print(np.hsplit(hs, 3))

#w pionie
print("W pionie")
print(np.vsplit(vs, 3))

W poziomie
[array([[1, 2],
       [4, 5],
       [7, 8]]), array([[ 3, 10],
       [ 6, 40],
       [ 9, 70]]), array([[20, 30],
       [50, 60],
       [80, 90]])]
W pionie
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 20, 30]]), array([[40, 50, 60],
       [70, 80, 90]])]


In [67]:
#konwersja na listę pythona
arr = np.arange(1,10)
lista = arr.tolist()
print(lista)
type(lista)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


list

In [73]:
#Fragmentowanie tablicy
arr = np.arange(0,10)
print(arr)
print(arr[3:6]) #ostatni znak jak w listach nie wchodzi w skład podtablicy
print(arr[-3:])
print(arr[2:7:2]) #od 2 do 7 co 2
print(arr[0])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5]
[7 8 9]
[2 4 6]
0


### Pandas
Pozwala na pracę z danymi panelowymi i tabelarycznymi.

In [2]:
#import biblioteki
import pandas as pd

In [80]:
df = pd.DataFrame() #stowrzenie pustego obiektu DataFrame - ramki danych
df.head() #kilka pierwszych rekordów

Empty DataFrame
Columns: []
Index: []

In [81]:
#tworzymy słownik z list i konwertujemy na DataFrame
dane = {"Imię":["Adam", "Agnieszka", "Zofia", "Zygmunt"], "Wiek":[19, 18, 27, 31]}
df = pd.DataFrame(dane) #tworzymy obiekt DataFrame
df.head()

Imię  Wiek
0       Adam    19
1  Agnieszka    18
2      Zofia    27
3    Zygmunt    31

In [82]:
#tworzymy listę ze słowników i konwertujemy na df
dane = [{"Imię":"Adam", "Wiek":19},{"Imię":"Agnieszka", "Wiek":18},{"Imię":"Zofia", "Wiek":27},{"Imię":"Zygmunt", "Wiek":31}]
df = pd.DataFrame(dane) #tworzymy obiekt DataFrame
df.head()

Imię  Wiek
0       Adam    19
1  Agnieszka    18
2      Zofia    27
3    Zygmunt    31

In [90]:
#tworzymy listę ze krotek i konwertujemy na df
dane = [('Adam',19), ('Agnieszka',18), ('Zofia', 27), ('Zygmunt', 31)]
df = pd.DataFrame(dane) #tworzymy obiekt DataFrame
df.head()
df = pd.DataFrame(dane, columns = ["Imię", "Wiek"]) #dodajemy nazwy kolumn
df.head()

Imię  Wiek
0       Adam    19
1  Agnieszka    18
2      Zofia    27
3    Zygmunt    31

In [4]:
#Obiekt Series z biblioteki Pandas

#tworzymy za pomc słownika
dict = {0:"Adam", 1:"Agnieszka", 2:"Zofia", 3:"Zygmunt"}
series = pd.Series(dict)
series

0         Adam
1    Agnieszka
2        Zofia
3      Zygmunt
dtype: object

In [6]:
#tworzymy za pomcą tablicy NumPy
arr = np.array([1,2,3,4,5,6])
series = pd.Series(arr)
series

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32

In [8]:
#za pomocą wartosci skalarnej
series = pd.Series(10, index = [0,1,2,3,4,5,6]) #7 x '10' o indeksach z listy
series

0    10
1    10
2    10
3    10
4    10
5    10
6    10
dtype: int64

In [55]:
#za pomocą wyboru kolumny
#https://github.com/PacktPublishing/Python-Data-Analysis-Third-Edition/blob/master/Chapter02/WHO_first9cols.csv
df = pd.read_csv(r"C:\Users\BPOL_1637\Documents\sgh\python\11. Pliki\WHO_first9cols.csv")
#df.head()
country_series = df['Country']
print(country_series.head())
print(type(country_series))

0    Afghanistan
1        Albania
2        Algeria
3        Andorra
4         Angola
Name: Country, dtype: object
<class 'pandas.core.series.Series'>


In [17]:
country_series[-5:] #zakres z serii

197               Vietnam
198    West Bank and Gaza
199                 Yemen
200                Zambia
201              Zimbabwe
Name: Country, dtype: object

In [21]:
print("Lista kolumn: \n", df.columns) #wyświetla listę kolumn z DataFrame

print("\nTypy danych: \n", df.dtypes) #wyświetla typy danych obiektu DataFrame

Lista kolumn: 
 Index(['Country', 'CountryID', 'Continent', 'Adolescent fertility rate (%)',
       'Adult literacy rate (%)',
       'Gross national income per capita (PPP international $)',
       'Net primary school enrolment ratio female (%)',
       'Net primary school enrolment ratio male (%)',
       'Population (in thousands) total'],
      dtype='object')

Typy danych: 
 Country                                                    object
CountryID                                                   int64
Continent                                                   int64
Adolescent fertility rate (%)                             float64
Adult literacy rate (%)                                   float64
Gross national income per capita (PPP international $)    float64
Net primary school enrolment ratio female (%)             float64
Net primary school enrolment ratio male (%)               float64
Population (in thousands) total                           float64
dtype: object


### Analiza danych obiektów DataFrame

|Metoda|Opis| 
|-----|-------|
|describes|podstawowe statystyki opisowe|
|count|zlicza elementy inne niż NaN|
|mad|odchylenie bezwzględne|
|median|mediana|
|min|minimum|
|max|maksimum|
|mode|dominanta|
|std|odchylenie standardowe|
|var|wariancja|
|skew|dkośność|
|kurt|kurtoza|

In [23]:
df.describe()

CountryID   Continent  Adolescent fertility rate (%)  \
count  202.000000  202.000000                     177.000000   
mean   101.500000    3.579208                      59.457627   
std     58.456537    1.808263                      49.105286   
min      1.000000    1.000000                       0.000000   
25%     51.250000    2.000000                      19.000000   
50%    101.500000    3.000000                      46.000000   
75%    151.750000    5.000000                      91.000000   
max    202.000000    7.000000                     199.000000   

       Adult literacy rate (%)  \
count               131.000000   
mean                 78.871756   
std                  20.415760   
min                  23.600000   
25%                  68.400000   
50%                  86.500000   
75%                  95.300000   
max                  99.800000   

       Gross national income per capita (PPP international $)  \
count                                         178.000000        
mean                                        11250.112360        
std                                         12586.753417        
min                                           260.000000        
25%                                          2112.500000        
50%                                          6175.000000        
75%                                         14502.500000        
max                                         60870.000000        

       Net primary school enrolment ratio female (%)  \
count                                     179.000000   
mean                                       84.033520   
std                                        17.788047   
min                                         6.000000   
25%                                        79.000000   
50%                                        90.000000   
75%                                        96.000000   
max                                       100.000000   

       Net primary school enrolment ratio male (%)  \
count                                   179.000000   
mean                                     85.698324   
std                                      15.451212   
min                                      11.000000   
25%                                      79.500000   
50%                                      90.000000   
75%                                      96.000000   
max                                     100.000000   

       Population (in thousands) total  
count                     1.890000e+02  
mean                      3.409964e+04  
std                       1.318377e+05  
min                       2.000000e+00  
25%                       1.328000e+03  
50%                       6.640000e+03  
75%                       2.097100e+04  
max                       1.328474e+06

In [24]:
df.count() #nie-NaN (niepuste) elementy

Country                                                   202
CountryID                                                 202
Continent                                                 202
Adolescent fertility rate (%)                             177
Adult literacy rate (%)                                   131
Gross national income per capita (PPP international $)    178
Net primary school enrolment ratio female (%)             179
Net primary school enrolment ratio male (%)               179
Population (in thousands) total                           189
dtype: int64

In [27]:
df.mad()

CountryID                                                    50.500000
Continent                                                     1.608960
Adolescent fertility rate (%)                                40.604616
Adult literacy rate (%)                                      16.556401
Gross national income per capita (PPP international $)     9600.489837
Net primary school enrolment ratio female (%)                13.094348
Net primary school enrolment ratio male (%)                  11.304017
Population (in thousands) total                           44131.698553
dtype: float64

In [25]:
df.median()

CountryID                                                  101.5
Continent                                                    3.0
Adolescent fertility rate (%)                               46.0
Adult literacy rate (%)                                     86.5
Gross national income per capita (PPP international $)    6175.0
Net primary school enrolment ratio female (%)               90.0
Net primary school enrolment ratio male (%)                 90.0
Population (in thousands) total                           6640.0
dtype: float64

In [28]:
df.min()

Country                                                   Afghanistan
CountryID                                                           1
Continent                                                           1
Adolescent fertility rate (%)                                       0
Adult literacy rate (%)                                          23.6
Gross national income per capita (PPP international $)            260
Net primary school enrolment ratio female (%)                       6
Net primary school enrolment ratio male (%)                        11
Population (in thousands) total                                     2
dtype: object

In [26]:
df.max()

Country                                                      Zimbabwe
CountryID                                                         202
Continent                                                           7
Adolescent fertility rate (%)                                     199
Adult literacy rate (%)                                          99.8
Gross national income per capita (PPP international $)          60870
Net primary school enrolment ratio female (%)                     100
Net primary school enrolment ratio male (%)                       100
Population (in thousands) total                           1.32847e+06
dtype: object

In [30]:
df['Continent'].mode()

0    2
dtype: int64

In [31]:
df['Net primary school enrolment ratio female (%)'].std()

17.78804656123047

In [32]:
df['Net primary school enrolment ratio male (%)'].var()

238.7399409955433

In [33]:
df['Net primary school enrolment ratio male (%)'].skew()

-1.9549092106498145

In [34]:
df['Net primary school enrolment ratio male (%)'].kurt()

4.529978546604902

In [36]:
#Grupowanie obiektów
df.groupby('Continent').mean()
df.groupby('Continent').median()['Net primary school enrolment ratio female (%)']

Continent
1    90.0
2    94.0
3    73.0
4    96.0
5    92.0
6    93.0
7    89.0
Name: Net primary school enrolment ratio female (%), dtype: float64

In [37]:
#Złączanie obiektów - odpowiednik join w SQL 

url_dest="https://raw.githubusercontent.com/PacktPublishing/Python-Data-Analysis-Third-Edition/master/Chapter02/dest.csv"
url_tips="https://raw.githubusercontent.com/PacktPublishing/Python-Data-Analysis-Third-Edition/master/Chapter02/tips.csv"
dest = pd.read_csv(url_dest)
tips = pd.read_csv(url_tips)

In [38]:
dest.head()

EmpNr       Dest
0      5  The Hague
1      3  Amsterdam
2      9  Rotterdam

In [39]:
tips.head()

EmpNr  Amount
0      5    10.0
1      9     5.0
2      7     2.5

In [41]:
#Złączenie wewnętrzne - inner join
df_inner = pd.merge(dest, tips, on = "EmpNr", how = "inner") #podajemy 2 tabele, klucz pom którym łączymy i typ złączenia
df_inner.head()

EmpNr       Dest  Amount
0      5  The Hague    10.0
1      9  Rotterdam     5.0

In [42]:
#Pełne złączenie zewnętrzne - full outer join
df_inner = pd.merge(dest, tips, on = "EmpNr", how = "outer")
df_inner.head()

EmpNr       Dest  Amount
0      5  The Hague    10.0
1      3  Amsterdam     NaN
2      9  Rotterdam     5.0
3      7        NaN     2.5

In [44]:
#Lewostronne złączenie zewnętrzne - left outer join
df_inner = pd.merge(dest, tips, on = "EmpNr", how = "left")
df_inner.head()

EmpNr       Dest  Amount
0      5  The Hague    10.0
1      3  Amsterdam     NaN
2      9  Rotterdam     5.0

In [45]:
#Prawostronne złączenie zewnętrzne - right outer join
df_inner = pd.merge(dest, tips, on = "EmpNr", how = "right")
df_inner.head()

EmpNr       Dest  Amount
0      5  The Hague    10.0
1      9  Rotterdam     5.0
2      7        NaN     2.5

In [48]:
#Wartości brakujące

#sprawdzanie wartości brakujących
pd.isnull(df).sum()
df.isnull().sum #drugi sposób

#usuwanie wartości brakujących
df.dropna(inplace = True) #inplace = True oznacza nadpisane obiektu bez wartości brakujących
df.info() #sprawdzamy listę obserwacji

#uzupełnianie brakujących wartości
df.fillna(0, inplace = True) #zastępujemy wartości NaN na 0
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 118 entries, 1 to 200
Data columns (total 9 columns):
 #   Column                                                  Non-Null Count  Dtype  
---  ------                                                  --------------  -----  
 0   Country                                                 118 non-null    object 
 1   CountryID                                               118 non-null    int64  
 2   Continent                                               118 non-null    int64  
 3   Adolescent fertility rate (%)                           118 non-null    float64
 4   Adult literacy rate (%)                                 118 non-null    float64
 5   Gross national income per capita (PPP international $)  118 non-null    float64
 6   Net primary school enrolment ratio female (%)           118 non-null    float64
 7   Net primary school enrolment ratio male (%)             118 non-null    float64
 8   Population (in thousands) total          

In [53]:
#Tabele przestawne
url = "https://raw.githubusercontent.com/PacktPublishing/Python-Data-Analysis-Third-Edition/master/Chapter02/purchase.csv"
purachses = pd.read_csv(url)
purachses.head(10)

Weather       Food     Price  Number
0    cold       soup  3.745401       8
1     hot       soup  9.507143       8
2    cold   icecream  7.319939       8
3     hot  chocolate  5.986585       8
4    cold   icecream  1.560186       8
5     hot   icecream  1.559945       8
6    cold       soup  0.580836       8

In [54]:
#podsumujmy ramkę danych
pd.pivot_table(purachses, values = 'Number', index = ['Weather'], columns = ['Food'], aggfunc = np.sum)
#values = kolumna, którą poddamy agregacji
#index = kolumna, wyświetlowa w wierszach do agregacji
#columns = kolumna, wyświetlona w formie kolumn w agregacji
#aggfunc = funkcje użyte do agregacji

Food     chocolate  icecream  soup
Weather                           
cold           NaN      16.0  16.0
hot            8.0       8.0   8.0

In [58]:
df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
                         "bar", "bar", "bar", "bar"],
                   "B": ["one", "one", "one", "two", "two",
                         "one", "one", "two", "two"],
                   "C": ["small", "large", "large", "small",
                         "small", "large", "small", "small",
                         "large"],
                   "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
                   "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})
df.head(10)

A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
2  foo  one  large  2  5
3  foo  two  small  3  5
4  foo  two  small  3  6
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9

In [57]:
table = pd.pivot_table(df, values='D', index=['A', 'B'],
                    columns=['C'], aggfunc=np.sum)
table

C        large  small
A   B                
bar one    4.0    5.0
    two    7.0    6.0
foo one    4.0    1.0
    two    NaN    6.0

In [59]:
table = pd.pivot_table(df, values='D', index=['A', 'B'],
                    columns=['C'], aggfunc=np.sum, fill_value=0) #fill_value zastępuje NaN
table

C        large  small
A   B                
bar one      4      5
    two      7      6
foo one      4      1
    two      0      6

In [60]:
table = pd.pivot_table(df, values=['D', 'E'], index=['A', 'C'],
                    aggfunc={'D': np.mean,
                             'E': [min, max, np.mean]}) #wiele agregacji
table

D    E               
               mean  max      mean  min
A   C                                  
bar large  5.500000  9.0  7.500000  6.0
    small  5.500000  9.0  8.500000  8.0
foo large  2.000000  5.0  4.500000  4.0
    small  2.333333  6.0  4.333333  2.0

In [66]:
#Daty

#zakres dat
pd.date_range('10-01-2022', periods = 180, freq = 'D') #tworzy zakres dat, od 1go paź 2022 do +180 dni, mm-dd-yyyy

#to_date - przekształcenie w znacznik czasowy
pd.to_datetime('10/1/2022')
pd.to_datetime(['20221002', '20221009', '20221016'], format = '%Y%m%d')

#obsługa nieznanych dat
pd.to_datetime(['20220101', "źle wpisałem datę"])
pd.to_datetime(['20220101', "źle wpisałem datę"], errors = 'coerce') #konwertuje źle wpisaną wartość na NaT - Not a Time

ParserError: Unknown string format: źle wpisałem datę

### Zadania

__Zadanie 1.__ <br>
Utwórz tablicę z użyciem biblioteki NumPy.<br>
Użyj części z funckji w oparciu o tak utworzoną tablicę.

__Zadanie 2.__ <br>
Utwórz obiekt DataFrame w oparciu o 3 sposoby pokazane na zajęciach. 

__Zadanie 3.__ <br>
Wybierz jakiś zbiór danych spośród dostępnych na: <br> 
https://archive.ics.uci.edu/ml/datasets.php.<br>
Utwóz obiekt DataFrame w oparciu o ten zbiór, przeanalizuj go i sprawdź ze względu na wartości brakujące. Usuń braki danych, jeżeli uznasz, że jest to niezbędne. 